### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by zunpan** [ChangcongWang/external-pdf#1]
请问如何配置The external command to open pdf？
是pdf阅读器exe的路径吗？

**Comment by ChangcongWang** [comment]
是的，例如这样`C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe`

当你点击pdf或pdf链接时右下角应该有弹窗显示你当前的文件位置，你可以检查下你pdf文件位置的格式位置是否正确，例如`D:/Paper/pdf/a.pdf`。然后可以用以下指令测试下能否在CMD中成功用外部exe打开pdf，前部分为`The external command to open pdf`需要使用双引号(部分路径存在空格)，后部分为所打开pdf文档。
```
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" D:/Paper/pdf/a.pdf
```
如果成功的话请关闭issue。如果失败或有其他疑问请提供更为具体的信息或案例，例如右下角弹窗内容及所使用pdf阅读器路径等。

**Comment by zunpan** [comment]
> 是的，例如这样`C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe`
> 
> 当你点击pdf或pdf链接时右下角应该有弹窗显示你当前的文件位置，你可以检查下你pdf文件位置的格式位置是否正确，例如`D:/Paper/pdf/a.pdf`。然后可以用以下指令测试下能否在CMD中成功用外部exe打开pdf，前部分为`The external command to open pdf`需要使用双引号(部分路径存在空格)，后部分为所打开pdf文档。
> 
> ```
> "C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" D:/Paper/pdf/a.pdf
> ```
> 
> 如果成功的话请关闭issue。如果失败或有其他疑问请提供更为具体的信息或案例，例如右下角弹窗内容及所使用pdf阅读器路径等。

谢谢，我设置成chrome浏览器可以打开pdf了
不过我一般用DrawboardPDF，不知道如何设置这个路径。

DrawboardPDF是个UWP应用，我尝试使用终端命令打开了阅读器，但是不知道怎么同时打开PDF
在我的机器上可以在终端`explorer.exe shell:AppsFolder\DRAWBOARD.DRAWBOARDPDF_gqbn7fs4pywxm!App` 打开阅读器

**Comment by ChangcongWang** [comment]
感谢你给本插件提供新思路，可以只获取文件位置使用默认阅读器打开，也不需要用户输入外部阅读器路径，这个功能等我有时间再进行完善下吧。

在此之前，你可以通过以下方法通过本插件使用UWP程序打开PDF。
1. 将你想使用的PDF阅读器设为默认阅读器
2. 在电脑的任一位置创建bat脚本，内容为`start "" %1`
3. 将阅读器路径修改为bat脚本位置，例如`D:\Desktop\1.bat`
4. 从vscode打开pdf，应该就没问题了，enjoy it


如果没有其他问题，可以关闭issue。

**Comment by ChangcongWang** [comment]
目前已经添加上新功能了，更新本插件，将command放空然后设置DrawboardPDF为默认pdf编辑器，应该可以正常工作了。(如果你不想设置DrawboardPDF为默认pdf阅读器，那我就没办法了，uwp应用的外部接口我是无从下手)

如果没有其他问题，可以关闭issue。(请无视上一条评论)

**Comment by zunpan** [comment]
谢谢！非常棒的插件
